### PR TITLE
Use empty mount path for first free drive letter

### PR DESCRIPTION
**Pull request by Lej77**
According to the documentation fo [FspFileSystemSetMountPoint](https://github.com/winfsp/winfsp/blob/7551193ad754c76eeabb5b7499d622d78ab39771/doc/WinFsp-API-winfsp.h.md) a null pointer can be used to not have to specify the drive letter that the filesystem should be mounted to. This PR exposes that functionality by mapping empty mount paths to a null pointer. This should be fine since empty paths aren't a valid mount path anyway. Alternatively the mount path could be an `Option`.

### CODE REVIEW

**Comment by chyyran** [comment]
I think I prefer the semantics of it being an `Option` here, I'm not too worried about API breakages at this point

**Comment by Lej77** [comment]
Actually I think `Option` doesn't work well with generics. So if you have `Option<S>` and supply a `None` then the type `S` can't be inferred so you have to specify it explicitly using for example turbofish.

We could not have the mount function being generic but it is probably better to have another function like `mount_to_free_drive_letter`.

**Comment by chyyran** [comment]
I don't think passing in  `None::<&OsStr>` would be so bad compared to special casing an empty mount path.

**Comment by chyyran** [comment]
Alternatively I'd be happy with something like

```rust
enum MountPoint<'a> {
  MountPoint(&'a OsStr),
  NextFreeDrive
}

impl <'a> From<&'a OsStr> for MountPoint<'a> {
 ...
}
```

as well. Unfortunately the identity `From` impl prevents a blanket implementation of `From<A> for MountPoint` but it calling `.as_ref().into()` might be better than turbofish?

**Comment by Lej77** [comment]
Well, I think an enum can work quite well. I tried it on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c66d7b8c212851d051ec37881123b72d).

**Comment by chyyran** [comment]
Ah nice, yeah that would work great.

**Comment by Lej77** [comment]
[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=90b05f14c23b74d9e2e3bca249c1ceae) is a more general version that allows owned values as arguments to the mount function.

**Comment by chyyran** [comment]
Yeah that looks good, feel free to PR it and I’d be happy to merge

**Comment by Lej77** [comment]
I have updated this PR to use the discussed enum solution.

**Comment by chyyran** [comment]
available in `0.10.0` and above. I pushed a release of `0.10.0` with these API changes and `async_trait` based async io, and `0.11.0` which uses afit/rptit for async io instead.

**Pull request merged**
